# --- QMIX specific parameters ---

# use epsilon greedy action selector
action_selector: "epsilon_greedy"
epsilon_start: 1.0
epsilon_finish: 0.05
epsilon_anneal_time: 50000

runner: "episode"
mac: "token_mac"
use_token: True

buffer_size: 5000

# update the target network every {} episodes
target_update_interval: 200

# use the Q_Learner to train
agent_output_type: "q"
learner: "token_q_learner"
optimizer: 'rmsprop'
double_q: True

mixer: "vdn"


# --- Agent parameters ---
agent: "token_wise_attn"
rnn_hidden_dim: 64      # Size of hidden state for default rnn agent
obs_agent_id: False     # Include the agent's one_hot id in the observation
obs_last_action: False  # Include the agent's last action (one_hot) in the observation

# --- Attention parameters ---
emb_dim: 32  # embedding dimension of attention
n_heads: 4   # head number of attention

name: "token_vdn_wise_attn"
