from .attention import Transformer, MultiHeadAttention
#from .sparse_attention import SparseTransformer, MultiHeadSparseAttention
#from .spotlight_attention import SpotlightTransformer, MultiHeadSpotlightAttention
#from .pattern_attention import PatternTransformer, MultiHeadPatternAttention
#from .inner_pattern_attention import InnerPatternTransformer, MultiHeadInnerPatternAttention
#from .latent_inner_pattern_attention import LatentInnerPatternTransformer, MultiHeadLatentInnerPatternAttention
#from .latent_pattern_attention import LatentPatternTransformer, MultiHeadLatentPatternAttention
