env: "particle"

env_args:
  benchmark: False
  map_name: "tag_8_1_2"
  num_good_agents: -1
  num_adversaries: -1
  num_landmarks: -1
  num_agents: -1
  episode_limit: 25
  agent_view_radius: -1
  score_function: "min"

test_greedy: True
test_nepisode: 32
test_interval: 10000
log_interval: 10000
runner_log_interval: 10000
learner_log_interval: 10000
save_model_interval: 200000
t_max: 1050000
